In [3]:
import pandas as pd
print("Pandas:", pd.__version__)

Pandas: 2.3.3

In [4]:
import sys
import pandas as pd
import numpy as np
import matplotlib
import seaborn as sns
import plotly

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Matplotlib:", matplotlib.__version__)
print("Seaborn:", sns.__version__)
print("Plotly:", plotly.__version__)
print("\nEverything is working!")

Python: 3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]
Pandas: 2.3.3
NumPy: 2.3.5
Matplotlib: 3.10.6
Seaborn: 0.13.2
Plotly: 6.3.0

Everything is working!

In [7]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("../data/raw_dataset.csv")

In [12]:
df.head()

,product_id,category,subcategory,material,color,size,season,style,price_usd,discount_percent,rating,review_count,stock_quantity,units_sold,return_rate
0,WC000001,Jeans,Skinny Jeans,Denim,Red,M,Summer,Business Casual,37.00,0,0.0,0,2,14,0.17
1,WC000002,Dresses,Wrap Dress,Cotton,White,M,Winter,Casual,59.12,10,0.0,0,13,31,0.13
2,WC000003,T-Shirts,V-Neck T-Shirt,Cotton,Purple,M,All Season,Casual,27.65,0,0.0,0,10,2,0.11
3,WC000004,Sweaters,Oversized Sweater,Wool,Brown,S,Winter,Formal,72.64,0,2.9,17,104,292,0.14
4,WC000005,Sweaters,Oversized Sweater,Wool,White,M,Winter,Minimalist,72.61,40,0.0,0,12,15,0.07

In [14]:
df.shape

(50000, 15)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   product_id        50000 non-null  object
 1   category          50000 non-null  object
 2   subcategory       50000 non-null  object
 3   material          50000 non-null  object
 4   color             50000 non-null  object
 5   size              50000 non-null  object
 6   season            50000 non-null  object
 7   style             50000 non-null  object
 8   price_usd         50000 non-null  float64
 9   discount_percent  50000 non-null  int64
 10  rating            50000 non-null  float64
 11  review_count      50000 non-null  int64
 12  stock_quantity    50000 non-null  int64
 13  units_sold        50000 non-null  int64
 14  return_rate       50000 non-null  float64
dtypes: float64(3), int64(4), object(8)
memory usage: 5.7+ MB

In [22]:
missing_values = df.isnull().sum()

print(missing_values)
print("Total missing values:", df.isnull().sum().sum())

product_id          0
category            0
subcategory         0
material            0
color               0
size                0
season              0
style               0
price_usd           0
discount_percent    0
rating              0
review_count        0
stock_quantity      0
units_sold          0
return_rate         0
dtype: int64
Total missing values: 0

In [23]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate product IDs:", df["product_id"].duplicated().sum())

Duplicate rows: 0
Duplicate product IDs: 0

In [24]:
categorical_columns = [
    "category",
    "subcategory",
    "material",
    "color",
    "size",
    "season",
    "style"
]

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts())

--- category ---
category
Dresses       6133
Tops          5909
T-Shirts      4520
Jeans         4467
Blouses       4016
Sweaters      3511
Trousers      3505
Skirts        3040
Jackets       3030
Activewear    2828
Loungewear    2460
Coats         1980
Cardigans     1571
Sets          1562
Jumpsuits     1468
Name: count, dtype: int64

--- subcategory ---
subcategory
Basic T-Shirt         1523
Graphic T-Shirt       1521
Bodysuit              1509
Crop Top              1478
V-Neck T-Shirt        1476
Long Sleeve Top       1462
Tank Top              1460
Peplum Blouse         1353
Wrap Blouse           1333
Button-Up Blouse      1330
Lounge Set            1309
Skinny Jeans          1167
Bootcut Jeans         1123
Wide-Leg Jeans        1095
Straight Jeans        1082
Midi Dress            1050
Mini Dress            1033
Wrap Dress            1032
Maxi Dress            1018
Bodycon Dress         1001
Shirt Dress            999
Wide-Leg Trousers      936
Crewneck Sweater       888
Oversized Sweater      881
Sweatpants             878
Knit Sweater           876
Turtleneck             866
Cargo Pants            860
Tailored Trousers      856
Straight Trousers      853
Mini Skirt             790
Pleated Skirt          766
Blazer                 765
Sleep Shirt            764
Maxi Skirt             760
Bomber Jacket          756
Track Pants            756
Denim Jacket           755
Leather Jacket         754
Midi Skirt             724
Sports Bra             703
Leggings               689
Athletic Top           680
Skirt Set              564
Button-up Cardigan     537
Cropped Cardigan       535
Wool Coat              507
Matching Suit          507
Long Cardigan          499
Utility Jumpsuit       497
Trench Coat            495
Evening Jumpsuit       491
Long Coat              490
Puffer Coat            488
Romper                 480
Name: count, dtype: int64

--- material ---
material
Cotton             14493
Cotton Blend        8399
Polyester           6773
Denim               5242
Polyester Blend     3986
Viscose             3501
Wool                3299
Linen               2279
Nylon               1115
Leather              913
Name: count, dtype: int64

--- color ---
color
Black     9948
White     7445
Beige     5093
Blue      5005
Navy      5003
Gray      4980
Green     2513
Brown     2507
Red       2495
Pink      2430
Purple    1305
Yellow    1276
Name: count, dtype: int64

--- size ---
size
M      15029
L      12297
S      10048
XS      5048
XL      5006
XXL     2572
Name: count, dtype: int64

--- season ---
season
Summer        10601
Autumn        10483
Winter        10109
Spring         9486
All Season     9321
Name: count, dtype: int64

--- style ---
style
Casual             12200
Business Casual     7793
Minimalist          6811
Formal              6725
Streetwear          5096
Bohemian            4355
Elegant             4192
Sporty              2828
Name: count, dtype: int64

In [25]:
df.describe()

,price_usd,discount_percent,rating,review_count,stock_quantity,units_sold,return_rate
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,61.858053,9.617800,3.056088,9.767320,37.515080,185.190660,0.107761
std,36.067137,12.369801,1.905743,32.783376,39.945939,530.180836,0.031606
min,12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,34.890000,0.000000,0.000000,0.000000,9.000000,21.000000,0.080000
50%,53.750000,0.000000,3.900000,2.000000,25.000000,59.000000,0.110000
75%,80.030000,15.000000,4.400000,8.000000,53.000000,163.000000,0.130000
max,275.560000,50.000000,5.000000,1639.000000,531.000000,31215.000000,0.230000

In [26]:
# Check minimum and maximum values of important numerical columns

numerical_columns = [
    "price_usd",
    "discount_percent",
    "rating",
    "review_count",
    "stock_quantity",
    "units_sold",
    "return_rate"
]

for column in numerical_columns:
    print(f"\n--- {column} ---")
    print("Minimum:", df[column].min())
    print("Maximum:", df[column].max())

--- price_usd ---
Minimum: 12.0
Maximum: 275.56

--- discount_percent ---
Minimum: 0
Maximum: 50

--- rating ---
Minimum: 0.0
Maximum: 5.0

--- review_count ---
Minimum: 0
Maximum: 1639

--- stock_quantity ---
Minimum: 0
Maximum: 531

--- units_sold ---
Minimum: 0
Maximum: 31215

--- return_rate ---
Minimum: 0.0
Maximum: 0.23

In [27]:
print("Invalid prices:", (df["price_usd"] < 0).sum())

print("Invalid discounts:",
      ((df["discount_percent"] < 0) | (df["discount_percent"] > 100)).sum())

print("Invalid ratings:",
      ((df["rating"] < 0) | (df["rating"] > 5)).sum())

print("Invalid review counts:",
      (df["review_count"] < 0).sum())

print("Invalid stock quantities:",
      (df["stock_quantity"] < 0).sum())

print("Invalid units sold:",
      (df["units_sold"] < 0).sum())

print("Invalid return rates:",
      ((df["return_rate"] < 0) | (df["return_rate"] > 1)).sum())

Invalid prices: 0
Invalid discounts: 0
Invalid ratings: 0
Invalid review counts: 0
Invalid stock quantities: 0
Invalid units sold: 0
Invalid return rates: 0

In [28]:
print("Rating = 0:", (df["rating"] == 0).sum())
print("Review count = 0:", (df["review_count"] == 0).sum())
print("Stock = 0:", (df["stock_quantity"] == 0).sum())
print("Units sold = 0:", (df["units_sold"] == 0).sum())
print("Discount = 0:", (df["discount_percent"] == 0).sum())

Rating = 0: 13357
Review count = 0: 13357
Stock = 0: 3715
Units sold = 0: 202
Discount = 0: 25117

In [29]:
df.dtypes

product_id           object
category             object
subcategory          object
material             object
color                object
size                 object
season               object
style                object
price_usd           float64
discount_percent      int64
rating              float64
review_count          int64
stock_quantity        int64
units_sold            int64
return_rate         float64
dtype: object

In [30]:
quality_summary = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str).values,
    "Missing_Values": df.isnull().sum().values,
    "Unique_Values": df.nunique().values
})

quality_summary

              Column Data_Type  Missing_Values  Unique_Values
0         product_id    object               0          50000
1           category    object               0             15
2        subcategory    object               0             55
3           material    object               0             10
4              color    object               0             12
5               size    object               0              6
6             season    object               0              5
7              style    object               0              8
8          price_usd   float64               0          12893
9   discount_percent     int64               0              9
10            rating   float64               0             33
11      review_count     int64               0            350
12    stock_quantity     int64               0            305
13        units_sold     int64               0           2041
14       return_rate   float64               0             19

In [31]:
print("Invalid prices:",
      (df["price_usd"] < 0).sum())

print("Invalid discounts:",
      ((df["discount_percent"] < 0) |
       (df["discount_percent"] > 100)).sum())

print("Invalid ratings:",
      ((df["rating"] < 0) |
       (df["rating"] > 5)).sum())

print("Invalid review counts:",
      (df["review_count"] < 0).sum())

print("Invalid stock quantities:",
      (df["stock_quantity"] < 0).sum())

print("Invalid units sold:",
      (df["units_sold"] < 0).sum())

print("Invalid return rates:",
      ((df["return_rate"] < 0) |
       (df["return_rate"] > 1)).sum())

Invalid prices: 0
Invalid discounts: 0
Invalid ratings: 0
Invalid review counts: 0
Invalid stock quantities: 0
Invalid units sold: 0
Invalid return rates: 0

In [32]:
print("Duplicate complete rows:",
      df.duplicated().sum())

print("Duplicate product IDs:",
      df["product_id"].duplicated().sum())

Duplicate complete rows: 0
Duplicate product IDs: 0

In [33]:
categorical_columns = [
    "category",
    "subcategory",
    "material",
    "color",
    "size",
    "season",
    "style"
]

for column in categorical_columns:
    print(f"\n===== {column.upper()} =====")
    print(sorted(df[column].unique()))

===== CATEGORY =====
['Activewear', 'Blouses', 'Cardigans', 'Coats', 'Dresses', 'Jackets', 'Jeans', 'Jumpsuits', 'Loungewear', 'Sets', 'Skirts', 'Sweaters', 'T-Shirts', 'Tops', 'Trousers']

===== SUBCATEGORY =====
['Athletic Top', 'Basic T-Shirt', 'Blazer', 'Bodycon Dress', 'Bodysuit', 'Bomber Jacket', 'Bootcut Jeans', 'Button-Up Blouse', 'Button-up Cardigan', 'Cargo Pants', 'Crewneck Sweater', 'Crop Top', 'Cropped Cardigan', 'Denim Jacket', 'Evening Jumpsuit', 'Graphic T-Shirt', 'Knit Sweater', 'Leather Jacket', 'Leggings', 'Long Cardigan', 'Long Coat', 'Long Sleeve Top', 'Lounge Set', 'Matching Suit', 'Maxi Dress', 'Maxi Skirt', 'Midi Dress', 'Midi Skirt', 'Mini Dress', 'Mini Skirt', 'Oversized Sweater', 'Peplum Blouse', 'Pleated Skirt', 'Puffer Coat', 'Romper', 'Shirt Dress', 'Skinny Jeans', 'Skirt Set', 'Sleep Shirt', 'Sports Bra', 'Straight Jeans', 'Straight Trousers', 'Sweatpants', 'Tailored Trousers', 'Tank Top', 'Track Pants', 'Trench Coat', 'Turtleneck', 'Utility Jumpsuit', 'V-Neck T-Shirt', 'Wide-Leg Jeans', 'Wide-Leg Trousers', 'Wool Coat', 'Wrap Blouse', 'Wrap Dress']

===== MATERIAL =====
['Cotton', 'Cotton Blend', 'Denim', 'Leather', 'Linen', 'Nylon', 'Polyester', 'Polyester Blend', 'Viscose', 'Wool']

===== COLOR =====
['Beige', 'Black', 'Blue', 'Brown', 'Gray', 'Green', 'Navy', 'Pink', 'Purple', 'Red', 'White', 'Yellow']

===== SIZE =====
['L', 'M', 'S', 'XL', 'XS', 'XXL']

===== SEASON =====
['All Season', 'Autumn', 'Spring', 'Summer', 'Winter']

===== STYLE =====
['Bohemian', 'Business Casual', 'Casual', 'Elegant', 'Formal', 'Minimalist', 'Sporty', 'Streetwear']

In [34]:
print("Products with rating > 0 but no reviews:",
      ((df["rating"] > 0) & (df["review_count"] == 0)).sum())

print("Products with reviews but rating = 0:",
      ((df["review_count"] > 0) & (df["rating"] == 0)).sum())

print("Products with units sold > 0 but zero stock:",
      ((df["units_sold"] > 0) & (df["stock_quantity"] == 0)).sum())

Products with rating > 0 but no reviews: 0
Products with reviews but rating = 0: 0
Products with units sold > 0 but zero stock: 3703

In [35]:
print("Price range:")
print(df["price_usd"].min(), "to", df["price_usd"].max())

print("\nRating range:")
print(df["rating"].min(), "to", df["rating"].max())

print("\nReturn rate range:")
print(df["return_rate"].min(), "to", df["return_rate"].max())

Price range:
12.0 to 275.56

Rating range:
0.0 to 5.0

Return rate range:
0.0 to 0.23

In [40]:
cleaned_df = df.copy()

print("Original rows:", len(df))
print("Working rows:", len(cleaned_df))

before_duplicates = len(cleaned_df)

cleaned_df = cleaned_df.drop_duplicates()

after_duplicates = len(cleaned_df)

print("Duplicate rows removed:", before_duplicates - after_duplicates)
print("Rows after duplicate removal:", after_duplicates)


missing_after_duplicates = cleaned_df.isnull().sum().sum()

print("Missing values after duplicate removal:",
      missing_after_duplicates)



text_columns = [
    "category",
    "subcategory",
    "material",
    "color",
    "size",
    "season",
    "style"
]

for column in text_columns:
    cleaned_df[column] = cleaned_df[column].str.strip()

Original rows: 50000
Working rows: 50000
Duplicate rows removed: 0
Rows after duplicate removal: 50000
Missing values after duplicate removal: 0

In [41]:
print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])
print("Missing values:", cleaned_df.isnull().sum().sum())
print("Duplicate rows:", cleaned_df.duplicated().sum())
print("Duplicate product IDs:",
      cleaned_df["product_id"].duplicated().sum())

Rows: 50000
Columns: 15
Missing values: 0
Duplicate rows: 0
Duplicate product IDs: 0

In [42]:
print("Price minimum:", cleaned_df["price_usd"].min())
print("Discount range:",
      cleaned_df["discount_percent"].min(),
      "to",
      cleaned_df["discount_percent"].max())

print("Rating range:",
      cleaned_df["rating"].min(),
      "to",
      cleaned_df["rating"].max())

print("Return rate range:",
      cleaned_df["return_rate"].min(),
      "to",
      cleaned_df["return_rate"].max())

Price minimum: 12.0
Discount range: 0 to 50
Rating range: 0.0 to 5.0
Return rate range: 0.0 to 0.23

In [43]:
cleaned_df.to_csv("../data/cleaned_dataset.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [48]:
print("RAW DATASET")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nCLEANED DATASET")
print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])


print("Total missing values:",
      cleaned_df.isnull().sum().sum())


print("Duplicate rows:",
      cleaned_df.duplicated().sum())

print("Duplicate product IDs:",
      cleaned_df["product_id"].duplicated().sum())

RAW DATASET
Rows: 50000
Columns: 15

CLEANED DATASET
Rows: 50000
Columns: 15
Total missing values: 0
Duplicate rows: 0
Duplicate product IDs: 0

In [49]:
print(cleaned_df.dtypes)

product_id           object
category             object
subcategory          object
material             object
color                object
size                 object
season               object
style                object
price_usd           float64
discount_percent      int64
rating              float64
review_count          int64
stock_quantity        int64
units_sold            int64
return_rate         float64
dtype: object

In [50]:
cleaned_df.head()

,product_id,category,subcategory,material,color,size,season,style,price_usd,discount_percent,rating,review_count,stock_quantity,units_sold,return_rate
0,WC000001,Jeans,Skinny Jeans,Denim,Red,M,Summer,Business Casual,37.00,0,0.0,0,2,14,0.17
1,WC000002,Dresses,Wrap Dress,Cotton,White,M,Winter,Casual,59.12,10,0.0,0,13,31,0.13
2,WC000003,T-Shirts,V-Neck T-Shirt,Cotton,Purple,M,All Season,Casual,27.65,0,0.0,0,10,2,0.11
3,WC000004,Sweaters,Oversized Sweater,Wool,Brown,S,Winter,Formal,72.64,0,2.9,17,104,292,0.14
4,WC000005,Sweaters,Oversized Sweater,Wool,White,M,Winter,Minimalist,72.61,40,0.0,0,12,15,0.07

In [51]:
cleaned_df.tail()

,product_id,category,subcategory,material,color,size,season,style,price_usd,discount_percent,rating,review_count,stock_quantity,units_sold,return_rate
49995,WC049996,Coats,Long Coat,Cotton,Black,L,Winter,Business Casual,67.13,10,3.7,1,54,23,0.12
49996,WC049997,Dresses,Midi Dress,Cotton Blend,White,M,Spring,Bohemian,81.27,20,4.3,2,154,52,0.14
49997,WC049998,Jeans,Wide-Leg Jeans,Cotton Blend,Red,L,Autumn,Minimalist,60.96,20,5.0,1,12,84,0.16
49998,WC049999,Sweaters,Knit Sweater,Wool,Beige,L,Autumn,Bohemian,79.54,20,4.4,2,4,140,0.08
49999,WC050000,Tops,Long Sleeve Top,Viscose,White,M,Winter,Elegant,19.72,0,0.0,0,29,6,0.06

## Data Cleaning Summary

The dataset was inspected and preprocessed using Pandas.

### Cleaning operations performed

1. Checked for missing values.
2. Checked for duplicate records.
3. Checked for duplicate product IDs.
4. Inspected categorical variables for consistency.
5. Checked numerical columns for invalid ranges.
6. Removed complete duplicate records where applicable.
7. Removed unnecessary leading/trailing spaces from categorical values.
8. Preserved the original raw dataset.
9. Saved the processed dataset separately as `cleaned_dataset.csv`.

### Dataset after preprocessing

- Rows: 50,000
- Columns: 15
- Missing values: 0
- Duplicate product IDs: 0